### PR TITLE
Create basic JSON schema for sections

### PR DESCRIPTION
**Pull request by Nilstrieb**
### What?

This PR adds a JSON schema for the basic section YAML schema.

### Why?

This allows people to use a JSON Schema in their YAML editor to make it easier to write the section YAML. I will write a guide on how to do this later.

### Testing?

I tested it locally with IntelliJs autocomplete in the editor. We could verify it in CI but I don't think thats important.

image

### CODE REVIEW

**Review by Lion-alt — APPROVED** [review]
LGTM

**Review by adrsch04 — APPROVED** [review]
LGTM

**Review by elion004 — APPROVED** [review]
Looks good

Could we discuss how to actually use it

**Comment by Nilstrieb** [comment]
> would be nice if there were a comment/explanation/link on how to enable schema validation for a certain yaml in intellij. like how can I use this when writing my section?

Already done last week: https://github.com/keykey7/fabbwled/wiki/Backend-conventions
I just forgot to link it

**Review by tamer545 — APPROVED** [review]
LGTM

**Review by kaibria — APPROVED** [review]
LGTM

**Review by Desi7 — APPROVED** [review]
Give it a go!

**Review by Rwael — CHANGES_REQUESTED** [review]
Changes look good, maybe combine commits?

**Review by Rwael — APPROVED** [review]
Saw that it squashes the commit, go ahead 😃

**Pull request merged**
