### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by corsin-lehre**
### What?
Update Readme to include figma file

### Why?
Because we need it

### How?
By adding it to the README

### Testing?
No testing required

### Anything Else?
This is so much fun :))))))))

[//]: # (for a sample see: https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)

### CODE REVIEW

**Review by tamer545 — APPROVED** [review]

**Review by Desi7 — APPROVED** [review]
Perfekt 👍

**Review by kaibria — APPROVED** [review]
good addtion

**Review by keykey7 — APPROVED** [review]
debatable project name :hankey:

**Review by nnikolajj — APPROVED** [review]

**Review by Oliver-was-taken — APPROVED** [review]
fand den Teil mit dem Text sehr gut 👍

**Review by Nilstrieb — APPROVED** [review]

**Review by Desi7 — APPROVED** [review]

**Comment by corsin-lehre** [comment]
thx for your comments

**Review by kaibria — APPROVED** [review]

**Pull request merged**
