### PR TITLE
Section Implementation

### PR DESCRIPTION
**Pull request by stevan04**
implemented sections: 328, 336, 340, 351

Issues:
328: https://github.com/keykey7/fabbwled/issues/197
336: https://github.com/keykey7/fabbwled/issues/226
340: https://github.com/keykey7/fabbwled/issues/959
351: https://github.com/keykey7/fabbwled/issues/956

### CODE REVIEW

**Review by Nilstrieb — APPROVED** [review]

**Review by elion004 — APPROVED** [review]
NICE :)

**Review by Rwael — APPROVED** [review]
Clean Code 👏🏻

**Review by lucasmillanm — APPROVED** [review]
seems okay

**Review by miolmi — APPROVED** [review]
cool👍

**Review by Lion-alt — APPROVED** [review]

**Pull request merged**
