### PR TITLE
Implement a reachability analysis for sections

### PR DESCRIPTION
**Pull request by Nilstrieb**
This detects unreachable sections and sections that don't terminate. This is basically like in a compiler. Compilers are cool!

### What?

This detects unreachable and unterminating sections to prevent mistakes.

### Why?

Because we have to implement 600 sections, so mistakes will be inevitable.

### How?

Recursively checks every action and whether it will terminate.

### Testing?

Several unit tests are included

### CODE REVIEW

**Comment by keykey7** [comment]
there are sections that can only be reached by using an item and there are multiple terminating sections where you die. you sure you want to implement such a verification?

**Comment by Nilstrieb** [comment]
> there are sections that can only be reached by using an item and there are multiple terminating sections where you die. you sure you want to implement such a verification?

The analysis is section local, only for the actions within a section.

**Review by MagischerWolf05 — APPROVED** [review]
👍

**Review by dbabvwid — APPROVED** [review]
But don't forget abount the DUMMY_ID

**Review by Desi7 — APPROVED** [review]
I think you have a great naming convention and it's good 👍

**Review by kimberlymo — APPROVED** [review]
Everything looks good and clean! 👍

**Review by Lion-alt — APPROVED** [review]
👍

**Pull request merged**
