### PR TITLE
Final Sections Noel

### PR DESCRIPTION
**Pull request by Noeell**
### What?
My last sections 😊 (implemented as good as possible)
### How?
writing some code 🤯
### Testing?
Section tests
### Anything Else?
closes: #529 
closes: #130 
closes: #525 
closes: #470 
closes: #203

### CODE REVIEW

**Review by JJoeeyy — APPROVED** [review]
Nice

**Review by nnikolajj — APPROVED** [review]
lgtm 🤠

**Review by Desi7 — APPROVED** [review]
Looks good to me 👍

**Review by oliver-jenny — APPROVED** [review]
lgtm

**Review by kimberlymo — APPROVED** [review]

**Review by MagischerWolf05 — COMMENTED** [review]
Looks Great

**Pull request merged**
