### PR TITLE
Add resurrection deal to yaml

### LINKED ISSUE #543: Add resurrection deal to yaml
**Is your feature request related to a problem? Please describe.**
Add the ability to use a resurrection deal and check if one exists to yaml.
**Describe the solution you'd like**
Add conditions and actions to implement this.
Add endpoint and integration tests for it and store the logic of it in a resurrection arrangement handler.
**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Lion-alt**
### What?
Add the ability to use a resurrection deal and check if one exists to yaml.
### Why?
Needed in many sections
### How?
Add conditions and actions to implement this.
Add endpoint and integration tests for it and store the logic of it in a resurrection arrangement handler.
### Testing?
Add endpoint and integration tests for it and store the logic of it in a resurrection arrangement handler.
### Anything Else?

closes #543

### CODE REVIEW

**Comment by Nilstrieb** [comment]
i love the resurrection deal in yaml here

**Review by Desi7 — APPROVED** [review]
Looks good to me 👍

**Review by tamer545 — APPROVED** [review]
Mhm mhm

**Review by dbabvwid — APPROVED** [review]

**Review by adrsch04 — APPROVED** [review]
looks good in the new yaml system

**Pull request merged**
