### PR TITLE
new issue template - branch was named automatically :(

### PR DESCRIPTION
**Pull request by Oliver-was-taken**
### What?
issue template

### Why?
current is bad for initial features

### Anything Else?

[//]: # (for a sample see: https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)

### CODE REVIEW

**Review by kaibria — APPROVED** [review]
Good idea with the issue template

**Review by JJoeeyy — APPROVED** [review]
I think this is a good way to describe the initial features.

**Review by corsin-lehre — APPROVED** [review]
I like these changes more than my own life

**Review by Desi7 — APPROVED** [review]
I like it that we have the opportunity to write down the tasks for the BE and the FE

**Review by Noeell — APPROVED** [review]
Good idea with the new template

**Review by tamer545 — APPROVED** [review]
I think this greatly simplifies the creation of new features!

**Pull request merged**
