### PR TITLE
new frontend stack

### PR DESCRIPTION
**Pull request by Oliver-was-taken**
### What?
new frontend stack

### Why?
initial setup wasn't to our likeing

### How?
npm :)

### Testing?
nah

### Screenshots (for frontend changes)
grafik

### Anything Else?
no

[//]: # (for a sample see: https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)

### CODE REVIEW

**Review by Noeell — APPROVED** [review]
Very good changes👍

**Review by corsin-lehre — COMMENTED** [review]
I live that we're using vite and materialui, Im sure you will be a Top G in no time

**Review by tamer545 — APPROVED** [review]
good work Oliver!✅😄

**Review by kaibria — APPROVED** [review]

**Review by nnikolajj — APPROVED** [review]
Super Sache

**Review by tamer545 — APPROVED** [review]
Good work Oliver!😄✅

**Pull request merged**
