### PR TITLE
Added .editorconfig

### PR DESCRIPTION
**Pull request by Lion-alt**
### What?
Added .editorconfig for better code style guidelines
### Why?
For better code style guidelines
### How?
Added .editorconfig

### CODE REVIEW

**Review by Nilstrieb — APPROVED** [review]

**Review by MagischerWolf05 — APPROVED** [review]
nice

**Review by tamer545 — APPROVED** [review]
nice guidelines!

**Review by Desi7 — APPROVED** [review]
Looking good, the more the better 👍

**Review by lucasmillanm — APPROVED** [review]
looking all beautiful etc

**Review by Rwael — APPROVED** [review]
Doesn't hurt 👍

**Pull request merged**
