### PR TITLE
Implement simple sections 156, 163, 165, 171, 173, 179, 180

### LINKED ISSUE #329: Section 156 Book 1
```
The priest looks you over. ‘I’m afraid we have no one skilled enough to cure you. However, I believe the Temple of Maka in Yellowport might be able to help. And the holy waters at Blessed Springs are known to be efficacious in this kind of case.’

Turn to 100
```

**Reference features required (if any)**
- \-

**Additional context**
grafik
grafik

### LINKED ISSUE #388: Section 163 Book 1
```
You hold up the pirate captain’s head. The guildmaster looks up expectantly, but his face quickly darkens.
‘This is not Amcha!! Everyone knows he has only one eye – this poor fellow is probably some beggar you killed in an alley somewhere. You think you can swindle the guild with this pathetic ruse! Out! Get out! And don’t come back until you bring me the head of Amcha One-Eye!’
The guildmaster has you removed by his guards, and you are dumped into the street.
Turn to 100.
```

**Reference features required (if any)**
* \-

**Additional context**
image

### LINKED ISSUE #392: Section 165 Book 1
```
A Sokaran war galley hails you and draws up alongside. ‘We’re coming aboard for an inspection!’ yells the captain of the galley. His men attempt to grapple your ship.
Let them turn to 552
Try to escape turn to 444
```

**Reference features required (if any)**
* \-

**Additional context**
image

### LINKED ISSUE #395: Section 167 Book 1
```
You lose your pursuers in the treacherous rocky passes of the mountains. Eventually, you reach the safety of the foothills.
Turn to 474.
```

**Reference features required (if any)**
* \-

**Additional context**
image

### LINKED ISSUE #399: Section 171 Book 1
```
You have soon laid the figures out like three logs on the village
green. They are badly hurt, but still alive. Now that you can get
a better look at them, you see that they are dusted all over with
flour, giving them a spectral appearance.
You summon the other villagers. At first they are loath to
venture out and inspect the three strangers, but the fact that you
survived convinces them there are no ghosts to worry about.
‘Why, it’s Old Megan!’ cries a man as he claps eyes on one
of the three. ‘And here’s Bradok the miller, and Lame Pootmar!
Why are they all covered in flour? Where’re the ghosts?’
You shake your head and sigh at the stupidity of the yokels.
‘There weren’t any ghosts,’ you explain. ‘It was these three all
along.’
Turn to 671.
```

**Reference features required (if any)**
* \-

**Additional context**
image

### LINKED ISSUE #401: Section 173 Book 1
```
You find yourself washed up on a rocky shore, battered and
cold, but lucky to be alive. You haul yourself up the beach on to
land. Fortunately for you, you find the village of Blessed Springs.
Turn to 510.
```

**Reference features required (if any)**
* \-

**Additional context**
image

### LINKED ISSUE #412: Section 179 Book 1
```
You claim that you have come to swear allegiance to Nergan, the rightful king of Sokara. Captain Vorkung is not convinced. He narrows his eyes suspiciously.
‘You’d better leave – now. Before I decide you are a spy, and have you shot!’
One of the archers looses a shaft, and an arrow thuds into the ground at your feet, quivering menacingly.
You realize it is time to leave, and climb down the mountain. 
Turn to 474.
```

**Reference features required (if any)**
* \-

**Additional context**
image

### LINKED ISSUE #414: Section 180 Book 1
```
You step through the archway. Immediately the symbols on the stone begin to glow with red-hot energy; your hair stands on end and your body tingles. A crackling nimbus of blue-white force engulfs you, the sky darkens and thunder and lightning crash and leap across the heavens. Suddenly, your vision fades, and everything goes black. 
When your sight returns, you find yourself outside the gates of a huge, fortified city. A guard starts in surprise at the sight of you. Then he shakes his head as if to clear it, sure he must have imagined what he just saw!
The gates open, and a troop of heavy cavalry canter past.
‘Make way for the Marlock City militia!’, says the guard.
When they have passed, you walk into the city. Turn to 100.
```

**Reference features required (if any)**
* \-

**Additional context**
image

### PR DESCRIPTION
**Pull request by miolmi**
### What?
Implemented simple sections 156, 163, 165, 167, 171, 173, 179, 180.

### Why?
Because they are needed for the process of the story.

### How?
Edited coresponding section yaml file.

### Testing?
is there

### Screenshots (for frontend changes)
no frontend change made.

### Anything Else?
closes #329 
closes #388
closes #392 
closes #395 
closes #399
closes #401
closes #412
closes #414

[//]: # (for a sample see: https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)

### CODE REVIEW

**Review by Nilstrieb — APPROVED** [review]

**Review by kimberlymo — APPROVED** [review]
lgtm 👍

**Review by Desi7 — APPROVED** [review]
Looks good to me 👍

**Review by adrsch04 — APPROVED** [review]
looks good; maybe add newlines between the sections to improve readability.

**Review by stevan04 — APPROVED** [review]
lgtm

**Pull request merged**
