### PR TITLE
Only make numbers clickable in turn to

### PR DESCRIPTION
**Pull request by Nilstrieb**
### What?

Only makes the number clickable instead of the entire text.

### Why?

It makes more sense.

### How?

By changing the thing

### Testing?

@JJoeeyy will test it in his branch

### Anything Else?

[//]: # (for a sample see: https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)

### CODE REVIEW

**Review by adrsch04 — APPROVED** [review]
lgtm

**Review by Lion-alt — APPROVED** [review]
lgtm

**Review by Desi7 — APPROVED** [review]
looking good 👍

**Review by JJoeeyy — APPROVED** [review]
Crazy

**Review by corsin-lehre — APPROVED** [review]
Wow

**Pull request merged**
