### PR TITLE
Refactor action building to be sane

### PR DESCRIPTION
**Pull request by Nilstrieb**
### What?

Refactors action building to use a registry based approach.

### Why?

This significantly reduces the previous exponential code duplication, making it a lot easier to add new action kinds.

### How?

By using a "registry" of actions, only a single place has to be edited.

### Testing?

All tests still pass.

### Anything Else?

[//]: # (for a sample see: https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)

### CODE REVIEW

**Review by Lion-alt — APPROVED** [review]
LGTM 👍

**Review by Desi7 — APPROVED** [review]
Looking good 👍

**Comment by Nilstrieb** [comment]
several action kinds are currently unimplemented, for example acquiring shards. This PR unblocks that

**Review by Noeell — APPROVED** [review]
Looks good!👏

**Pull request merged**
