### PR TITLE
Feature/kai sections

### PR DESCRIPTION
**Pull request by kaibria**
### Anything Else?
closes: #120 
closes: #653 
closes: #929 
closes: #930 
closes: #931 
closes: #932 
closes: #933 
closes: #934 
closes: #935 
closes: #546 
closes: #936 
closes: #937 
closes: #938 
closes: #939 
closes: #940 
closes: #941 
closes: #942 
closes: #943

### CODE REVIEW

**Review by JJoeeyy — APPROVED** [review]
looks good to me

**Review by oliver-jenny — APPROVED** [review]
Looks good, fix tests :octocat:

**Review by nnikolajj — APPROVED** [review]
Lgtm 🧑‍🌾
The Test that failed is SectionServiceTest.byIdInvalid
I think its because the Section 680 is now implemented but i dont really know and dont really know how to fix.
The SectionValidation test is ok, so its not your fault
But you could delete the test or fix it

**Review by Noeell — APPROVED** [review]
Please fix test

**Review by miolmi — APPROVED** [review]
lgtm.
great work my friend 👍

**Pull request merged**
