### PR TITLE
Feature/sections joey

### PR DESCRIPTION
**Pull request by JJoeeyy**
### What?
Sections 577-612

### How?
yaml

### Testing?
Section tests

### Anything Else?
closes: #87
closes: #93 
closes: #126 
closes: #159 
closes: #877 
closes: #878 
closes: #879 
closes: #880 
closes: #881 
closes: #882  
closes: #883 
closes: #884 
closes: #885 
closes: #886 
closes: #887 
closes: #888 
closes: #889 
closes: #890 
closes: #891 
closes: #892 
closes: #893 
closes: #894 
closes: #895 
closes: #896 
closes: #897 
closes: #898 
closes: #899 
closes: #900 
closes: #901 
closes: #902 
closes: #903 
closes: #904 
closes: #905 
closes: #906 
closes: #907 
closes: #908 

[//]: # (for a sample see: https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)

### CODE REVIEW

**Review by nnikolajj — APPROVED** [review]
lgtm

**Review by oliver-jenny — APPROVED** [review]
_lgtm_

**Review by Noeell — APPROVED** [review]
🫡

**Review by kimberlymo — APPROVED** [review]

**Review by elion004 — APPROVED** [review]
LGTM

**Review by Nilstrieb — APPROVED** [review]

**Pull request merged**
