### PR TITLE
section 23, 28, 36

### PR DESCRIPTION
**Pull request by Lion-alt**
### What?
Implemented sections 23, 28 and 36
### Why?
Because there needed
### How?
Edited section yaml files
### Testing?
Already there
### Anything Else?
closes https://github.com/keykey7/fabbwled/issues/238
closes https://github.com/keykey7/fabbwled/issues/213
closes https://github.com/keykey7/fabbwled/issues/200

### CODE REVIEW

**Review by adrsch04 — APPROVED** [review]
looks good

**Review by Desi7 — APPROVED** [review]
Looks good to me 👍

**Review by Nilstrieb — CHANGES_REQUESTED** [review]

**Review by MagischerWolf05 — APPROVED** [review]
Top welldone!😎

**Review by Rwael — APPROVED** [review]
Good

**Pull request merged**
