### PR TITLE
Verify syntactical validity of JSON schema

### PR DESCRIPTION
**Pull request by Nilstrieb**
### What?

Verify that the schema is valid JSON

### Why?

We've had cases where it wasn't, that's not good.

### How?

By writing a test.

### Testing?

I changed the schema to make it invalid and the test broke.

### CODE REVIEW

**Review by Lion-alt — APPROVED** [review]
LGTM 👍

**Review by Noeell — APPROVED** [review]
Thanks! This will help us to improve code quality

**Review by Desi7 — APPROVED** [review]
looking good 👍 nice that you tested it (I'll take your word for it)

**Review by kaibria — APPROVED** [review]
good for validation! lgtm

**Pull request merged**
