### PR TITLE
implemented section-326

### PR DESCRIPTION
**Pull request by stevan04**
###
implemented the section 326

### Why?
is needed

### How?
with the section-yaml

### Anything Else?

[//]: # (for a sample see: https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)

### CODE REVIEW

**Review by elion004 — COMMENTED** [review]
looks nice

**Review by Nilstrieb — CHANGES_REQUESTED** [review]
Looks good.
Can you add the issue link in the description, like `closes #XXXX`. This will automatically close the issue when this is merged.

**Review by Desi7 — APPROVED** [review]
Looks good to me

**Review by kimberlymo — APPROVED** [review]
lgtm 👍

**Review by Lion-alt — APPROVED** [review]
Looks good

**Review by lucasmillanm — APPROVED** [review]
seems okay

**Pull request closed without merging**
