### PR TITLE
Update and rename initial_feature to initial_feature.md

### PR DESCRIPTION
**Pull request by Oliver-was-taken**
same as 1 minute ago...

### CODE REVIEW

**Review by tamer545 — APPROVED** [review]
Good change

**Review by JJoeeyy — APPROVED** [review]
same as 1 minute ago...

**Review by Desi7 — APPROVED** [review]
okay

**Review by corsin-lehre — APPROVED** [review]
I love this change more than my father will ever love me

**Review by nnikolajj — APPROVED** [review]

**Review by kaibria — APPROVED** [review]

**Review by kaibria — COMMENTED** [review]
good change

**Pull request merged**
