### PR TITLE
remaining sections

### LINKED ISSUE #244: Section 38 Book 1
```
Heavy black clouds race towards you across the sky, whipping
the waves into a frenzy. The crew mutter among themselves
fearfully. If you have the blessing of Alvir and Valmir, which
confers Safety from Storms, you can ignore the storm. Cross off
the blessing and turn to 209.
Otherwise the storm hits with full fury. Roll one die if your
ship is a barque, two dice if it is a brigantine, or three dice if a
galleon. Add one to the roll if the crew’s quality is good; add 2 if
it is excellent.
Score 1-3 Ship sinks turn to 325
Score 4-5 The mast splits turn to 397
Score 6-20 You weather the storm turn to 209
```

**Reference features required (if any)**
#230 - Blessing
Adventure Sheet (cross of blessing)
Inventory (which ship Player owns)
Roll Dices (1 to 3)

**Additional context**
Needs the blessing of Alvir and Valmir and afterwards the Adventure Sheet to cross it off.
As well as the Inventory of the Player to check which ship(barque, brigantine or galleon) the Player owns, to determind the amount of dices to roll (1 to 3).

### LINKED ISSUE #245: Section 39 Book 1
```
You and some of your crew clamber aboard the wreck. You
find some dead sailors amid the wreckage. Their bodies are
curiously bloated. Make a SCOUTING roll at Difficulty 9.
Successful SCOUTING roll turn to 194
Failed SCOUTING roll turn to 465
```

**Reference features required (if any)**
SCOUNTING Dice Roll
Character Abilities

**Additional context**
Character Abilieties for the SCOUTING Roll

### LINKED ISSUE #246: Section 40 Book 1
```
You take the Book of the Seven Sages to Pyletes the Sage at
the Gold Dust Tavern. He thanks you effusively for bringing it
to him. Your reward is secret learning from the temple of
Molhern, god of knowledge. Add 1 to the ability of your
choice. Also gain the title Illuminate of Molhern – write this in
the Titles and Honours box on your Adventure Sheet. Lose the
codeword Artefact and cross off the Book of the Seven Sages.
Turn to 10.
```

**Reference features required (if any)**
Inventory
Character Ability
Adventure Sheet (Aquire Title)
Codeword

**Additional context**
The Player should have the Book of the Seven Sages in his Inventory and cross it out after giving it away.
The Player may add 1 to any Ability he desires. As well as the Adventure Sheet to auire a Title and to cross off the codeword (Artefact ).

### LINKED ISSUE #248: Section 42 Book 1
```
Two hulking shapes appear out of the shadows as if from
nowhere. They are hideous creatures – manlike, standing on
two legs, but with the tail and hairy features of a gigantic rat.
Their yellowing teeth snap at you as they lunge for you; the
ratmen also wield wicked-looking shortswords in their hands.
‘Gut the human!’ yells one of them in a bestial voice.
You must fight them, both at once, as if they were one
opponent. If you have some rat poison, you can add 3 to your
dice rolls. Cross the rat poison off the Adventure Sheet if you
use it.
Two Ratmen, COMBAT 6, Defence 9, Stamina 9
If you win, turn to 423. If you lose, turn to 308.
```

**Reference features required (if any)**
Inventory
Dice Roll
#41 COMBAT System

**Additional context**
Iventory to check if the Player has some rat poison.
Dice Roll to fight the enemies with the Fighting System

### LINKED ISSUE #249: Section 43 Book 1
```
You must fight. Luckily, your magic weapon will be effective.
Tomb Guardian, COMBAT 6, Defence 8, Stamina 12
If you win, turn to 490. If you lose, you are dead, unless you
have a resurrection deal.
```

**Reference features required (if any)**
Inventory
Enemy stats
Player stats
COMBAT System

**Additional context**
Inventory of Player to get his magical sword and if the Player has a resurrection deal. Then the Fighting System and the Abilities of Enemy and Player.
If the Player loses and has no resurrection deal he dead.

### LINKED ISSUE #251: Section 45 Book 1
```
The little girl runs off before you can talk to her. You thread
your way through the pitted tombstones and brooding crypts of
the cemetery, under a pale moon that bathes the graveyard in a
sickly, pallid light.
Suddenly, a foul stench fills your nostrils, and a figure rises
up out of the shadows! Yellow eyes glow with feral blood-lust,
and the creature sinks its black teeth into your arm before you
can react. Lose 4 Stamina.
If you still live, you have been infected. Not that you have a
Disease (Ghoulbite). Until you find a cure, you must subtract
one from your SANCTITY, COMBAT, and CHARISMA abilities
(no ability can drop below one). The ghoul, a rotting, walking
corpse, lunges for you again.
Fight it turn to 617
Invoke the power of the gods turn to 144
Use salt and iron filings, if you have any turn to 303
```

**Reference features required (if any)**
Character Ability
Inventory

**Additional context**
Character Abilities to lose some points.
And Inventory to check if the Player has salt and iron to turn to the given page.

### LINKED ISSUE #252: Section 46 Book 1
```
Lose the codewords Almanac, Brush and Eldritch if you have
them.
You can invest money in multiples of 100 Shards. The guild
will buy and sell commodities on your behalf using this money
until you return to collect it. ‘Don’t forget that you can lose
money as well,’ mutters a sullen merchant.
Write the sum you are investing in the box here – or
withdraw a sum invested previously. Then turn to 405.
```

**Reference features required (if any)**
Codeword
Money and Shards
Guild

**Additional context**
The Game has a Guild where the Player can invest or withdraw their money/shards. Those will be saved in the Inventory of the Player.
Lose some Codewords at the beginning.
grafik

### LINKED ISSUE #254: Section 48 Book 1
```
The warden is in charge of security. ‘We have had an
unfortunate, umm… accident,’ he says worriedly. ‘In the crypt
below the temple we sometimes experiment with the corpses of
the dead – you know, the occasional zombie, part of the rituals
in honour of the particular aspect of Nagil we revere here. It
seems a ghoul has escaped from these pits, and is terrorizing the
city at night. We’d rather someone like you sorted the problem
out before the city militia got to hear of it. Destroy it and bring
me the ghoul’s head.’
If you want to take up the mission, record the codeword
Ague. ‘Search for it at night!’ says the warden as you leave. Turn
to 100.
```

**Reference features required (if any)**
Codeword

**Additional context**
IF the Player is up for the mission write the Codeword down.

### LINKED ISSUE #255: Section 49 Book 1
```
Not taking any chances, you charge the soldier, yelling a warcry.
He starts back in astonishment. Just then, several archers pop up
from behind the rocks above, and let loose a volley of arrows.
One takes you in the leg. Lose 3 Stamina points.
If you still live, you fall to one knee, and the soldier melts
away into the rocks. Alone, and wounded in the leg, you cannot
climb upwards. You have to go back down though the descent
will be difficult with a dodgy leg. Roll a die, adding 1 if you
have some climbing gear.
Score 1-3 turn to 529
Score 4-6 turn to 474
```

**Reference features required (if any)**
Character Ability
Dice Roll
Inventory

**Additional context**
Character Ability to lose some Stamina. Inventory for the climbing gear and Roll the Dice.

### LINKED ISSUE #257: Section 51 Book 1
```
The war galley puts alongside, and grappling hooks fly through
the air, fastening your ships together. The captain leaps across
and his men swarm on to your ship. A battle ensues. Roll three
dice if you are a Warrior, or two dice if you belong to any other
profession. Add your Rank to this roll. Then, if your crew is
poor quality, subtract 2 from the total. If the crew quality is
good, add 2. If the crew quality is excellent, add 3.
Score 0-4 Calamity; you are killed turn to 680
Score 5-9 Crushing defeat;
lose 1-6 Stamina turn to 153
Score 10-13 A draw turn to 242
Score 14+ Outright victory turn to 62
```

**Reference features required (if any)**
Character Infos (Profession, Rank)
Dice Roll
Crew Quality

**Additional context**
Will need the Profession and Rank from the Player. As well as the Crew Quality and Dices to Roll.

### LINKED ISSUE #258: Section 52 Book 1
```
If you are an initiate it costs only 10 Shards to purchase Lacuna’s
blessing. A non-initiate must pay 25 Shards. Cross off the money
and mark SCOUTING in the Blessings box on your Adventure
Sheet.
The blessing works by allowing you to try again when you
fail a SCOUTING roll. It is good for only one reroll. When you
use the blessing, cross it off your Adventure Sheet. You can only
have one SCOUTING blessing at any one time. Once it is used
up, you can return to any branch of the Temple of Lacuna to
buy a new one.
When you are finished here, turn to 544.
```

**Reference features required (if any)**
Shards System
Inventory
Blessing (use only once)

**Additional context**
Shareds System to buy the blessing. Store the blessing in the Players Inventory.

### LINKED ISSUE #259: Section 53 Book 1
```
The creature bursts open in death, spilling a black inky cloud
into the water. The sac in which this ink is kept falls free from
its body. You can take the ink sac if you wish – note it on your
Adventure Sheet. You also find coral jewellery worth about 15
Shards. Nothing else occurs during your foray into the depths,
so you return to land. You climb back up the path that leads to
the clifftop tor without incident.
Take the road to Trefoille turn to 602
Take the road to Marlock City turn to 166
```

**Reference features required (if any)**
Inventory

**Additional context**
Store the items, if wanted, in the Inventory of the Player.

### LINKED ISSUE #261: Section 55 Book 1
```
You remember that this is a trap set up by the cannibal cultists of
Badogor. While one pretends to be hurt, two other skulk in the
shadows, waiting to ambush the curious. Forewarned you are
able to take them by surprise. You cut one down in seconds and
the figure on the ground runs off with a shriek of terror. The
third cultist, however, turns to fight you.
Cultist, COMBAT 3, Defence 5, Stamina 7
If you win, you find a bag of pearls on his body. Turn to 10.
```

**Reference features required (if any)**
COMBAT System
Inventory

**Additional context**
Fight the Enemy and if you win take the pearls in your Inventory.

### LINKED ISSUE #418: Section 58 Book 1
```
He doesn’t notice you hiding in the shadowy doorway of a
nearby derelict house. As he passes, you step out and attack,
taking him completely by surprise. He goes down with your first
blow. Searching him, you find 25 Shards, which you can take if
you wish. Then you flip up his eyepatch. Nestling in the eye
socket is a sparkling gem, a flame opal. You pluck it free. Note
the flame opal eye on your Adventure Sheet and delete the
codeword Barnacle. Quickly, you haul the body into the shadows
and head for the city centre. Turn to 400.
```

**Reference features required (if any)**
Inventory, 25 Shards (optional)
Adventure Sheet, flame opal eye
Codeword, Barnacle

**Additional context**
none

### LINKED ISSUE #419: Section 59 Book 1
```
Your deft fingers find a false spine of carved wood among the
titles in the bookcase. Pressing it, you hear a click and the
bookcase swings out from the wall. Beyond lies a hidden room
where you find a verdigris key. Note this on your Adventure
Sheet if you decide to take it.
Leave at once turn to 10
Go upstairs to find Lauria turn to 386
Wait for her to return turn to 534
```

**Reference features required (if any)**
Inventory, verdigris key (optional)

**Additional context**
none

### LINKED ISSUE #420: Section 60 Book 1
```
You are crossing the wild country of north-east Sokara. Roll
one die.
Score 1 or 2 Caught in an animal trap! Lose 2 Stamina
Score 3 or 4 Nothing happens
Score 5 or 6 Attacked by a wolf, and must fight.
Wolf, COMBAT 3, Defence 5, Stamina 7.
If you win, you get a wolf pelt.
When you are ready, you can go:
North turn to 518
South turn to 458
West turn to 201
```

**Reference features required (if any)**
COMBAT System
Diece Roll (just one)

**Additional context**

### LINKED ISSUE #421: Section 61 Book 1
```
‘Wait,’ you cry, ‘I have seen the light! I wish to join your cult!’
‘What!’ yells the chef. Then his shoulders sag in resignation.
‘We cannot refuse a new member,’ says the leader with
obvious disappointment. ‘And we cannot eat our own people,’
he adds sadly.
A short ceremony later – fortunately, the initiation does not
involve any cannibalistic rites – and you are a full member of the
Cult of Badogor. Write Unspeakable Cultist in the Titles and
Honours box on your Adventure Sheet. You lose 1 point of
SANCTITY permanently for joining such a vile cult.
You take your leave, and they wish you well, all smiles and
friendship.
‘Remember, never say his name! And don’t forget to bring
us new recruits,’ says the leader. ‘And some people for dinner!’
adds the chef.
Hastily, you head for the city centre. Turn to 10.
```

**Reference features required (if any)**
Adventure Sheet, 'Unnspeakable Cultist' in titles and honours box
PLayer stats, SANCTITY

**Additional context**
none

### LINKED ISSUE #422: Section 62 Book 1
```
The Sokarans surrender. Their captain has been killed in the
battle, and his marines have had the fight knocked out of them.
The war galley isn’t carrying any cargo, but you find an
officer’s pass on the body of the captain, and a chest in his
cabin, which contains 150 Shards. You have to hand out 50
Shards to your crew, but you can add 100 Shards to your
Adventure Sheet. You leave the galley to limp back to
Yellowport while you sail on. Turn to 439.
```

**Reference features required (if any)**
Adventure Sheet, 100 Shards

**Additional context**
none

### LINKED ISSUE #424: Section 64 Book 1
```
Your amateurish tinkering sets the trap off, and the chest
explodes! You take the full force of the blast – lose 5 Stamina
points. If you are still alive, you also find that the contents of the
chest have been vaporized – except for a sturdy metal scroll case,
containing a piece of ancient religious text about the gods of
Uttaku. You discover from the scroll that one of the gods of the
Uttakin is called Ebron, and that he has fourteen angles. Note
the scroll of Ebron on your Adventure Sheet if you wish to
take it. Turn to 10.
```

**Reference features required (if any)**
Player stats, Stamina
Adventure Sheet, scroll of Ebron (optional)

**Additional context**
none

### LINKED ISSUE #427: Section 67 Book 1
```
Your ship is thrown about like flotsam and jetsam. When the
storm subsides, you take stock. Much has been swept overboard
– you lose 1 Cargo Unit, if you had any, of your choice. Also,
the ship has been swept way off course and the mate has no idea
where you are. ‘We’re lost at sea, Cap’n!’ he moans.
Turn to 90.
```

**Reference features required (if any)**
Inventory, lose ShipCargo of choice

**Additional context**
none

### LINKED ISSUE #428: Section 68 Book 1
```
To renounce the worship of Alvir and Valmir, you must pay 30
Shards in compensation to the priesthood.
The priest simply points to a ship limping into harbour – its
shattered masts, torn sails and battered hull mute testimony to its
storm-tossed voyage.
‘The captain did not revere the Twin Gods,’ whispers the
coral-jewelled priest darkly.
Do you want to change your mind? If you are determined to
renounce your faith, pay the 30 Shards and delete Alvir and
Valmir from the God box on your Adventure Sheet.
Turn to 154.
```

**Reference features required (if any)**
Inventory, Shards (optional)
Adventure Sheet, Alvir and Valmir from the God box (optional)

**Additional context**
none

### LINKED ISSUE #429: Section 69 Book 1
```
To renounce the worship of Tyrnai, you must pay 50 Shards to
the warrior priests, and suffer the Ceremony of the Wrathful
Blow. A priest will strike you once – it is better to be struck by a
priest than by Tyrnai himself!
If you are determined to renounce your initiate status, pay
the 50 Shards, delete Tyrnai from the God box on your
Adventure Sheet. The High Priest smashes you across the jaw,
saying ‘I’m doing you a favour – believe me!’ Lose 1 Stamina
point. If you earlier arranged a resurrection here, it is cancelled
with no refund.
When you are finished, turn to 526.
```

**Reference features required (if any)**
Inventory, Shards
Adventure Sheet, Tyrnai from God box
Player stats, Stamina

**Additional context**
none

### LINKED ISSUE #430: Section 70 Book 1
```
Your ship is thrown about like flotsam and jetsam. When the
storm subsides, you take stock. Much has been swept overboard
– you lose 1 Cargo Unit, if you had any, of your choice. Also,
the ship has been swept way off course and the mate has no idea
where you are. ‘We’re lost at sea, Cap’n!’ he moans.
Turn to 90.
```

**Reference features required (if any)**
Inventory, lose ShipCargo of choice

**Additional context**
none

### PR DESCRIPTION
**Pull request by Desi7**
### What?
All section that where left implemented, that at least the player can jump to the next section and will not be stoped

### Why?
To add story for our game

### How?
With code

### Testing?
Nope

### Anything Else?
closes #244 
closes #245 
closes #246 
closes #248 
closes #249 
closes #251 
closes #252 
closes #254 
closes #255 
closes #257 
closes #258 
closes #259 
closes #261 
closes #418 
closes #419 
closes #420 
closes #421 
closes #422 
closes #424 
closes #427 
closes #428 
closes #429 
closes #430

### CODE REVIEW

**Review by kimberlymo — APPROVED** [review]
LGTM 👍

**Review by Nilstrieb — APPROVED** [review]
:shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit:

**Review by Noeell — APPROVED** [review]
👌

**Review by elion004 — APPROVED** [review]
LGTM :)

**Review by Lion-alt — APPROVED** [review]
LGTM 👍

**Review by MagischerWolf05 — APPROVED** [review]
Looks Good

**Pull request merged**
