### PR TITLE
implement new game button

### PR DESCRIPTION
**Pull request by JJoeeyy**
### What?
Implement the new Game button, to start a new game.

### Anything Else?

[//]: # (for a sample see: https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)

### CODE REVIEW

**Review by tamer545 — APPROVED** [review]
good button

**Review by nnikolajj — APPROVED** [review]
💂

**Review by kaibria — APPROVED** [review]
looks good

**Review by corsin-lehre — APPROVED** [review]
I think Linus torvalds can't program this good

**Review by Noeell — APPROVED** [review]
link looks good 👌

**Review by oliver-jenny — APPROVED** [review]
lgtm

**Pull request merged**
