### PR TITLE
feat: implement sections

### PR DESCRIPTION
**Pull request by tamer545**
### What?
Implement my sections
### Anything Else?

[//]: # (for a sample see: https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)

### CODE REVIEW

**Review by oliver-jenny — APPROVED** [review]
lgtm

**Review by JJoeeyy — APPROVED** [review]
lgtm

**Review by kaibria — APPROVED** [review]
lgtm

**Review by nnikolajj — APPROVED** [review]
lgtm

**Review by Lion-alt — APPROVED** [review]
LGTM 👍

**Review by Noratrieb — APPROVED** [review]

**Review by Desi7 — APPROVED** [review]
lgtm 👍

**Review by Desi7 — APPROVED** [review]
lgtm 👍

**Review by kimberlymo — APPROVED** [review]
Almost everything looks good, but a choice can have two items or more, not one ;)
Had the same issue :P

**Pull request closed without merging**
