### PR TITLE
Make section controller cross origin

### PR DESCRIPTION
**Pull request by Nilstrieb**
### What?

Makes the section controller cross origin

### Why?

To make it cross origin

### How?

by making it cross origin

### Testing?

let @JJoeeyy do requests (I copied it from the other controller so I don't think it needs testing)

### Anything Else?

[//]: # (for a sample see: https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)

### CODE REVIEW

**Review by Lion-alt — APPROVED** [review]
Nice helpful change 👍

**Review by MagischerWolf05 — APPROVED** [review]
love it😍So Effective yet so clean

**Review by dbabvwid — CHANGES_REQUESTED** [review]
Please add comments.

**Review by lucasmillanm — APPROVED** [review]
CORSSS

**Review by dbabvwid — APPROVED** [review]

**Review by Rwael — APPROVED** [review]
Looks good. Port is hardcoded but default so it's ok

**Pull request merged**
