### PR TITLE
S325 360 implementation

### PR DESCRIPTION
**Pull request by stevan04**
### What?
implemented remaining sections from S325 to S360.

### Why?
needed for the final game.

### How?
all remaining sections where implemented via the yaml-template, but some of the don't have any logik. (still playable)

### Anything Else?

closes:

- https://github.com/keykey7/fabbwled/issues/11
- https://github.com/keykey7/fabbwled/issues/31
- https://github.com/keykey7/fabbwled/issues/197
- https://github.com/keykey7/fabbwled/issues/204
- https://github.com/keykey7/fabbwled/issues/207
- https://github.com/keykey7/fabbwled/issues/211
- https://github.com/keykey7/fabbwled/issues/214
- https://github.com/keykey7/fabbwled/issues/221
- https://github.com/keykey7/fabbwled/issues/226
- https://github.com/keykey7/fabbwled/issues/233
- https://github.com/keykey7/fabbwled/issues/956
- https://github.com/keykey7/fabbwled/issues/957
- https://github.com/keykey7/fabbwled/issues/958
- https://github.com/keykey7/fabbwled/issues/959
- https://github.com/keykey7/fabbwled/issues/960
- https://github.com/keykey7/fabbwled/issues/961
- https://github.com/keykey7/fabbwled/issues/962
- https://github.com/keykey7/fabbwled/issues/963
- https://github.com/keykey7/fabbwled/issues/964
- https://github.com/keykey7/fabbwled/issues/965
- https://github.com/keykey7/fabbwled/issues/966
- https://github.com/keykey7/fabbwled/issues/967
- https://github.com/keykey7/fabbwled/issues/968
- https://github.com/keykey7/fabbwled/issues/969
- https://github.com/keykey7/fabbwled/issues/970
- https://github.com/keykey7/fabbwled/issues/971
- https://github.com/keykey7/fabbwled/issues/972

### CODE REVIEW

**Review by Nilstrieb — APPROVED** [review]

**Review by Noeell — APPROVED** [review]
👍

**Review by Desi7 — APPROVED** [review]
Looks good to me 👍

**Review by MagischerWolf05 — APPROVED** [review]
looks good

**Review by kimberlymo — APPROVED** [review]

**Review by elion004 — APPROVED** [review]
LGTM

**Review by Lion-alt — APPROVED** [review]
LGTM 👍

**Pull request merged**
