### PR TITLE
Turn YAML into section nodes

### PR DESCRIPTION
**Pull request by Nilstrieb**
### What?

do the thing

### Anything Else?

[//]: # (for a sample see: https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)

### CODE REVIEW

**Review by lucasmillanm — APPROVED** [review]
Seems alright

**Review by Desi7 — APPROVED** [review]
looking good 👍

**Review by stevan04 — APPROVED** [review]
looks good to me, maybe a bit more description to make it more understandable

**Review by elion004 — APPROVED** [review]
lgtm :)

**Pull request merged**
