### PR TITLE
Sections Oliver

### PR DESCRIPTION
**Pull request by oliver-jenny**
### What?
Sections..
- 631
- 632
- 645
- 648
- 613
- 617
- 623
- 633
- 635
- 639

### Why?
- Playability

### Anything Else?
closes: #149 
closes: #218 
closes: #516
closes: #519
closes: #38 
closes: #53 
closes: #118  
closes: #220 
closes: #231 
closes: #510 
closes: #50 

[//]: # (for a sample see: https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)

### CODE REVIEW

**Review by Nilstrieb — APPROVED** [review]
merge whenever you want

**Review by Lion-alt — APPROVED** [review]
LGTM 👍

**Review by Noeell — APPROVED** [review]
🫡

**Review by miolmi — APPROVED** [review]
lgtm

**Pull request merged**
