### PR TITLE
added new sections

### LINKED ISSUE #287: Section 74 Book 1
```
A fisherman will take you all the way to Yellowport for 15
Shards. Cross the money of your Adventure Sheet. Amazingly,
despite the apparent fragility of the small vessel, you arrive
without incident. Turn to 10.
```

**Reference features required (if any)**
[Shard System](https://github.com/keykey7/fabbwled/issues/215)

### LINKED ISSUE #289: Section 75 Book 1
```
The high priest takes you to a private chamber.
‘You may be just what the temple needs,’ he says, ‘a good,
old-fashioned thief! There is a suit of armour made entirely of
gold – ceremonial only of course. Nevertheless, we would like
to, er, have it donated to us.’
‘I see,’ you reply, ‘and where is the armour?’
‘Well that’s the tricky part – it’s in the Temple of Tyrnai, in
Caran Baru. In fact, it’s worn by the idol of Tyrnai himself in
the temple! Can you bring us the gold chain mail of Tyrnai? In
return, we will instruct you in the roguish arts.’
If you want to take up the mission for the Temple of Sig,
record the codeword Armour. Turn to 235
```

### LINKED ISSUE #291: Section 78 Book 1
```
Make a SCOUTING roll at Difficulty 10.
Successful SCOUTING roll turn to 524
Failed SCOUTING roll turn to 415
```

### LINKED ISSUE #292: Section 79 Book 1
```
Make a SCOUTING roll at Difficulty 14, as you try to lose them
in the tunnels. It is hard because they know the layout better
than you do.
      Successful SCOUTING roll turn to 224
      Failed SCOUTING roll turn to 381
```

### LINKED ISSUE #306: Section 89 Book 1
```
The undead pirate reaches for you, but it is too slow. Then it
speaks, its voice seeming to sound inside your head.
‘Damn you, and your kind, thieving sea centaur! I curse you
forever – may you never swim again in the seas you love. You
will walk for the rest of your life as a human, doomed to wander
the surface world, unable to find the peace of coral caves!’
Quickly, you swim away, unable to believe your luck! What
a convenient curse. You find yourself already changing back to a
human, and you make it to your ship, coughing and spluttering.
Your crew haul you aboard. The gems are worth 300 Shards –
add that much to your money. You sail on, lucky to be still
human. Turn to 507
```

**Reference features required (if any)**
[shard system](https://github.com/keykey7/fabbwled/issues/215)

### LINKED ISSUE #307: Section 90 Book 1
```
Your ship is limping through unknown waters. The sun beats
down, and the wind drops to a whisper.
‘What direction, Cap’n?’ asks the bosun.
Make a SCOUTING roll at Difficulty 10.
Successful SCOUTING roll turn to 633
Failed SCOUTING roll turn to 484
```

### LINKED ISSUE #310: Section 91 Book 1
```
He smiles and takes you into the Gambler’s Den. It is a smokefilled casino, full of all kinds of dubious characters, playing cards
and dice. If you want to gamble, decide how much you want to
bet, to a maximum of 20 Shards, and roll two dice.
Score 2 win five times your bet
Score 3-4 win twice your bet
Score 5-9 lose your bet
Score 10-11 win twice your bet
Score 12 win five times your bet
When you are ready to leave, put a tick in the box and turn to
109, unless the box is already ticked, in which case turn to 100.
```

**Reference features required (if any)**
[dice mechanics](https://github.com/keykey7/fabbwled/issues/19)

### LINKED ISSUE #314: Section 92 Book 1
```
He falls dead at your feet. Searching him, you find 25 Shards
you can take if you wish. Then you flip up his eyepatch.
Nestling in the eye-socket is a sparkling gem, a flame opal. You
pluck it free. Note the flame opal eye on your Adventure
Sheet and lose the codeword Barnacle. You hurry off, before a
patrol arrives. Turn to 400.
```

**Reference features required (if any)**
[code words](https://github.com/keykey7/fabbwled/issues/188)

### LINKED ISSUE #317: Section 93 Book 1
```
If you have the codeword Azure, turn to 359 immediately. If
not, read on.
A mad beggar, covered in sores and grime, accosts you in the
street. ‘O noble one, aid me for the love of the gods!’ he rants,
frothing at the mouth and gesticulating wildly. ‘ I need coins to
eat, food to spend, and blessings to wear!’
Ignore him and return to city centre turn to 10
Give him 5 Shards turn to 227
Bless him turn to 632
```

**Reference features required (if any)**
[codewords](https://github.com/keykey7/fabbwled/issues/188)

### LINKED ISSUE #319: Section 94 Book 1
```
At last, the golem is defeated. You manage to get into the
temple without being noticed by anyone else. Inside, it is cool
and dark, filled with an unearthly stillness. You reach forward to
strip the armour off the idol of Tyrnai.
Make a THIEVERY roll at Difficulty 12.
Successful THIEVERY roll turn to 509
Failed THIEVERY roll turn to 228
```

### LINKED ISSUE #321: Section 96 Book 1
```
One of the militiamen kicks over a table, blocking your escape.
You set your back to a corner of the room and grimly prepare to
fight for your life. Fight them one at a time:
First Militiaman, COMBAT 4, Defence 7, Stamina 5
Second Militiaman, COMBAT 4, Defence 7, Stamina 4
Third Militiaman, COMBAT 4, Defence 7, Stamina 5
If you win, turn to 432. If you surrender, turn to 218.
```

**Reference features required (if any)**
[fighting system](https://github.com/keykey7/fabbwled/issues/41)

### LINKED ISSUE #323: Section 97 Book 1
```
You climb down a narrow track to the beach. The sea pounds
the rocky shore, and the spray lashes your face. A mournful, yet
utterly captivating singing suddenly fills your ears. You look out
to sea, and spot several mermaids and mermen, cavorting in the
surf.
‘Come, come to us…’ one of them calls in a lilting voice
that fills you with a yearning desire to plunge into the sea and
swim out to them.
Make a SANCTITY roll at Difficulty 10.
Successful SANCTITY roll turn to 584
Failed SANCTITY roll turn to 159
```

### LINKED ISSUE #327: Section 100 Book 1
```
Marlock City is a huge sprawling metropolis, enclosed in a
fortified wall said to have been built one thousand years ago by
the ancient Shadar Empire. It is the capital city of Sokara.
Marlock City was once known as Sokar, until General Grieve
Marlock led the army in bloody revolt against the old king,
Corin VII, and had him executed. The general renamed the city
after himself – it is now a crime to call it Sokar.
The general lives in the old king’s palace, and calls himself
the Protector-General of all Sokara. Whereas the old king was
corrupt, the general rules with a fist of iron. Some people like
the new regime; others are royalists, still loyal to Nergan, the
heir to the throne, who has gone into hiding somewhere.
Outside the city gates hang the bodies of many dead people
– labels around their necks read: ‘Rebels, executed by the state
for the good of the people’.
‘You’d best behave yourself if you don’t want to end up like
one of them,’ grates a guardsman, nodding towards the swinging
corpses, as you pass through the great eagle-headed gates of
Marlock City.
You can buy a town house in Marlock City for 200 Shards.
Owning a house gives you a place to rest, and to store
equipment. If you buy one, cross off 200 Shards and tick the
box by the town house option.
To leave Marlock City by sea, or to buy or sell ships and
cargo, go the harbourmaster.
Visit the Three Rings Tavern turn to 158
Visit the temple of Alvir and Valmir turn to 154
Visit the temple of Nagil turn to 71
Visit the temple of Sig turn to 235
Visit the temple of Elnir turn to 568
Visit the market turn to 396
Visit the harbourmaster turn to 142
Go to the merchants’ guild turn to 571
Explore the city turn to 138
Visit your town house ! (if box ticked) turn to 434
Visit the House of Priests turn to 535
Visit the general’s palace turn to 601
Travel east towards Trefoille turn to 377
Head south-east towards the Shadar Tor turn to 166
Follow the River Grimm north turn to 99
Journey north into the Curstmoor turn to 175
Head west to the River Grimm delta turn to 579
```

### LINKED ISSUE #328: Section 101 Book 1
```
You yell the name of their god again and again. The cultists clap
their hands over their ears, hopping about in horror.
‘Aargh!’ howls the leader. ‘Stop your blaspheming, you
heathen devil!’
In their confusion, you make it to your equipment. Now
you can fight your way out. Make a COMBAT roll of Difficulty
13. If you fail, turn to 204. If you succeed, you manage to fight
your way to freedom with the loss of 4 Stamina points and head
back to town, turn to 10
```

**Reference features required (if any)**
[fighting system](https://github.com/keykey7/fabbwled/issues/41)

### LINKED ISSUE #331: Section 102 Book 1
```
If you have the codeword Defend, turn to 655 immediately. If
not, read on.
‘What are you doing back here,’ asks Grieve Marlock,
angrily. ‘You should be defending the citadel! You know, that
castle in the Pass of Eagles, up north! Get back there and talk to
Orin Telana!’
If you have a coded missive, turn to 677. Otherwise, you
are shown out in short order. Turn to 100.
```

**Reference features required (if any)**
[codewords](https://github.com/keykey7/fabbwled/issues/188)

### LINKED ISSUE #333: Section 104 Book 1
```
Lose the codewords Almanac, Brush and Eldritch if you have
them. You can invest money in multiples of 100 Shards. The
guild will sell and buy commodities on your behalf using this
money until you return to collect it.
‘Don’t forget that you can lose money as well,’ mutters a
sullen merchant who leaves the guild penniless.
Write the sum you are investing in the box here – or
withdraw a sum invested previously. Then turn back to 571.

box with money invested
```

**Reference features required (if any)**
[shard system](https://github.com/keykey7/fabbwled/issues/215)
[codewords ](https://github.com/keykey7/fabbwled/issues/188)

**Additional context**
The image below is an example on how the box can look like:
example-box

### LINKED ISSUE #334: Section 105 Book 1
```
You will have to fight it.
Scorpion Shaman, COMBAT 5, Defence 8, Stamina 9
If you win, turn to 532. If you lose, your adventures are over
unless you have a resurrection deal.
```

**Reference features required (if any)**
[fighting system](https://github.com/keykey7/fabbwled/issues/41)

### LINKED ISSUE #335: Section 106 Book 1
```
Cross off the money. The young man smiles ingratiatingly, and
hands you the pearls. Make a MAGIC roll at a Difficulty of 10.
Successful MAGIC roll turn to 306
Failed MAGIC roll turn to 489
```

### LINKED ISSUE #336: Section 107 Book 1
```
If you are an initiate it costs only 10 Shards to purchase Tyrnai’s
blessing. A non-initiate must pay 25 Shards. Cross off the money
and mark COMBAT in the Blessings box on your Adventure
Sheet.
The blessing works by allowing you to try again when fail a
COMBAT roll. It is good for only one reroll. When you use the
blessing, cross it off your Adventure Sheet. You can only have
one COMBAT blessing at any one time. Once it is used up, you
can return to any branch of the temple of Tyrnai to buy a new
one.
When you are finished, turn to 282
```

**Reference features required (if any)**
[shard system](https://github.com/keykey7/fabbwled/issues/215)
blessings

### LINKED ISSUE #339: Section 108 Book 1
```
That night, your sleep is restless. You dream a most vivid dream.
You are attacked by a gigantic sea monster, a mighty octopoid
thing that encircles the ship with tree-like tentacles and pulls it
under the waves. You sink into the bottle-green depths until
you are caught in a glowing golden net.
You wake in an undersea palace of multi-coloured coral,
with mermaids to attend you. They lead you past trident-armed
merman guards into a great hall. Seated upon two giant shells,
like thrones, are the king and queen of the deep, with green
hair, sea-grey eyes, and crowns of pale gold. Shoals of iridescent
angel fish dart about in an intricate flashing dance of colour,
dancing for the rulers of the land beneath the waves. In awe,
you bow before them.
The queen indicates that you should entertain them, for they
are bored! A silver flute appears in your hands. Make a
CHARISMA roll at Difficulty 11.
Successful CHARISMA roll turn to 132
Failed CHARISMA roll turn to 457
```

### PR DESCRIPTION
**Pull request by kimberlymo**
### What?
resolves #339 
resolves #335 
resolves #328 
resolves #323 
resolves #319 
resolves #317 
resolves #314 
resolves #310 
resolves #307 
resolves #306 
resolves #292 
resolves #291 
resolves #289 
resolves #321 
resolves #331 
resolves #333 
resolves #334 
resolves #336 
resolves #327 
resolves #287 

### How?
Java as well as YAML
### Anything Else?
Sorry for the big PR ;)
Not all of them are fully implemented because of missing features or time limit
[//]: # (for a sample see: https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)

### CODE REVIEW

**Review by Nilstrieb — APPROVED** [review]

**Review by Nilstrieb — APPROVED** [review]

**Review by Desi7 — APPROVED** [review]
Looking good 👍

**Review by Noeell — APPROVED** [review]
Looks like you worked hard🤯

**Review by MagischerWolf05 — APPROVED** [review]
looks good

**Review by elion004 — APPROVED** [review]
LGTM

**Review by Lion-alt — APPROVED** [review]
LGTM 👍

**Pull request merged**
