### PR TITLE
began with adding tickboxes

### PR DESCRIPTION
**Pull request by Lion-alt**
### What?
Add tickboxes and checking of them to yaml
### Why?
Is needed in section yamls
### How?
Edited section-schema.json and more.

### CODE REVIEW

**Review by Rwael — APPROVED** [review]
Nice Niche-Functionality 🐱‍🐉

**Review by adrsch04 — APPROVED** [review]
cool feature

**Review by Nilstrieb — APPROVED** [review]

**Review by tamer545 — APPROVED** [review]
Finally

**Review by kaibria — APPROVED** [review]
cool feature

**Pull request merged**
