### PR TITLE
Added Shard Action

### PR DESCRIPTION
**Pull request by Rwael**
### Anything Else?

[//]: # (for a sample see: https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)

### CODE REVIEW

**Review by Nilstrieb — APPROVED** [review]
This is a good first step
Doesn't implement the logic yet but it's a first step

**Review by Lion-alt — APPROVED** [review]
Looks good 👍

**Review by tamer545 — APPROVED** [review]
Lgtm!

**Review by kaibria — APPROVED** [review]
lgtm

**Review by Desi7 — APPROVED** [review]
For the Future please write a short summary in the description, but looks good to me 👍

**Review by miolmi — APPROVED** [review]

**Pull request merged**
