### PR TITLE
Add sections for every dev

### PR DESCRIPTION
**Pull request by kimberlymo**
### What?
Created YAML files for each dev as discussed on 04.09.2023

### Why?
So that every dev has their own workspace.

[//]: # (for a sample see: https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)

### CODE REVIEW

**Review by Nilstrieb — APPROVED** [review]

**Review by Nilstrieb — CHANGES_REQUESTED** [review]
Can you also add CODEOWNERS like in #71?

**Review by Rwael — APPROVED** [review]
Very Good!

**Review by Nilstrieb — APPROVED** [review]
We can do it in a separate PR.

**Review by tamer545 — APPROVED** [review]
I like the idea of having an own sector for my sections. Like a personal workspace :)

**Review by kaibria — APPROVED** [review]
Good idea for better structure

**Pull request merged**
