### PR TITLE
Revert "Disable some section validation"

### PR DESCRIPTION
**Pull request by dbabvwid**
Reverts keykey7/fabbwled#973

### CODE REVIEW

**Comment by dbabvwid** [comment]
Should be removed

**Review by MagischerWolf05 — APPROVED** [review]
LGTM

**Review by Desi7 — APPROVED** [review]
david told me so

**Review by Nilstrieb — CHANGES_REQUESTED** [review]
can you add the motivation for this change?

**Review by kimberlymo — APPROVED** [review]
David held me at gunpoint to approve this PR

**Comment by Nilstrieb** [comment]
that's concerning...

**Comment by Nilstrieb** [comment]
are you okay?

**Comment by dbabvwid** [comment]
Dont concern your self with such trivial matters

**Comment by dbabvwid** [comment]
Nils is a fbwiba

**Pull request closed without merging**
