### PR TITLE
implemented sections

### PR DESCRIPTION
**Pull request by elion004**
### What?
implemented sections

### Why?
to finish project

### How?
in yaml

### Anything Else?

closes:
- https://github.com/keykey7/fabbwled/issues/27
- https://github.com/keykey7/fabbwled/issues/236
- https://github.com/keykey7/fabbwled/issues/264
- https://github.com/keykey7/fabbwled/issues/265
- https://github.com/keykey7/fabbwled/issues/266
- https://github.com/keykey7/fabbwled/issues/272
- https://github.com/keykey7/fabbwled/issues/273
- https://github.com/keykey7/fabbwled/issues/647
- https://github.com/keykey7/fabbwled/issues/648
- https://github.com/keykey7/fabbwled/issues/649
- https://github.com/keykey7/fabbwled/issues/651
- https://github.com/keykey7/fabbwled/issues/652
- https://github.com/keykey7/fabbwled/issues/655
- https://github.com/keykey7/fabbwled/issues/656
- https://github.com/keykey7/fabbwled/issues/657
- https://github.com/keykey7/fabbwled/issues/658
- https://github.com/keykey7/fabbwled/issues/659
- https://github.com/keykey7/fabbwled/issues/660
- https://github.com/keykey7/fabbwled/issues/661
- https://github.com/keykey7/fabbwled/issues/662
- https://github.com/keykey7/fabbwled/issues/665
- https://github.com/keykey7/fabbwled/issues/667
- https://github.com/keykey7/fabbwled/issues/668
- https://github.com/keykey7/fabbwled/issues/669
- https://github.com/keykey7/fabbwled/issues/671

### CODE REVIEW

**Review by Nilstrieb — APPROVED** [review]

**Review by Desi7 — APPROVED** [review]
Looks good to me 👍

**Review by kimberlymo — APPROVED** [review]

**Review by stevan04 — APPROVED** [review]
good

**Review by Lion-alt — APPROVED** [review]
LGTM 👍

**Review by MagischerWolf05 — APPROVED** [review]
Looks Good tom me

**Pull request merged**
