### PR TITLE
Disable some section validation

### PR DESCRIPTION
**Pull request by Nilstrieb**
We need to SHIPIT

### What?

disable some validation

### Why?

SHIPIT :shipit: 

### How?

no more validation

### Testing?

no

### Anything Else?

[//]: # (for a sample see: https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)

### CODE REVIEW

**Review by Lion-alt — APPROVED** [review]
LGTM 👍

**Review by dbabvwid — COMMENTED** [review]
Why would you do that?

**Review by kimberlymo — APPROVED** [review]
Good idea for improving implementation time! But this should be removed in the future ;)

**Review by Desi7 — APPROVED** [review]
i guess 👍

**Comment by Nilstrieb** [comment]
APPROVE

**Comment by Nilstrieb** [comment]
> Good idea for improving implementation time! But this should be removed in the future ;)

future?

**Review by adrsch04 — APPROVED** [review]
lgtm

**Review by dbabvwid — APPROVED** [review]
ich bin glp

**Comment by Nilstrieb** [comment]
> Why would you do that?

Our goal is to ship as many sections as possible while not really caring about them being correct. So removing some validation is fine.

**Review by oliver-jenny — APPROVED** [review]
lgtm :shipit:

**Comment by kimberlymo** [comment]
> > Good idea for improving implementation time! But this should be removed in the future ;)
> 
> future?

there is no future, past or present

**Pull request merged**
