### PR TITLE
Add sections to CODEOWNERS in Backend

### PR DESCRIPTION
**Pull request by Nilstrieb**
### What?

Adds a codeowner for each section in the backend.

### Why?

Because they own the code and are responsible for it.

### How?

By adding them to the CODEOWNERS file.

### Testing?

No.

[//]: # (for a sample see: https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)

### CODE REVIEW

**Review by keykey7 — APPROVED** [review]
Good idea. Might make sense to pre-create all those empty packages (with an empty .gitignore file in it) such that ppl start following the convention.

**Review by Lion-alt — COMMENTED** [review]
Very good idea for better project structure.

**Comment by Nilstrieb** [comment]
I'm actually not sure whether we really want to structure it like this. See #72, needs more discussion

**Review by tamer545 — APPROVED** [review]
I like the idea of it!

**Review by kaibria — APPROVED** [review]

**Review by elion004 — COMMENTED** [review]
nice idea

maybe we want to write that directly in the 'README' file? Or reference the file in it?

**Review by JJoeeyy — APPROVED** [review]

**Review by nnikolajj — APPROVED** [review]
Ja finde ich gut, jedoch würde ich wünschen, wenn man auf Deutsch schreibt, da es einfacher ist, und so sicherlich weniger Meinungsverschiedenheiten gibt. 
Was ist denn der Grund dafür?

**Review by Oliver-was-taken — CHANGES_REQUESTED** [review]
I like the Idea with the YAML more than the java option and I think we should validate the options before starting with the implementations. Also I don't think that everyone is resposible that their actions/chapters are added to the dataset. imo thats a job for the backend-people :|

**Review by Noeell — CHANGES_REQUESTED** [review]
I would prefer the option with yaml files, because it significantly increases readability!

**Comment by tamer545** [comment]
> Ja finde ich gut, jedoch würde ich wünschen, wenn man auf Deutsch schreibt, da es einfacher ist, und so sicherlich weniger Meinungsverschiedenheiten gibt. Was ist denn der Grund dafür?

English is the standard language for programming

**Comment by Nilstrieb** [comment]
Superseeded by #182

**Pull request closed without merging**
