### PR TITLE
Implemented easy sections

### LINKED ISSUE #51: Section 505 Book 1
```
Cross the silver nugget off your Adventure Sheet.‘Excellent,’ says the dragon, catching the nugget in one of itsclawed forelimbs.With that, it rolls over, and dives down into the lake. At thelast second, its tail whips up out of the water, inches from yourface.You could reach out and grab it, if you wanted to.Catch the tailturn to 362. Leave it well alone turn to 561
```

**Reference features required (if any)**
Catch the tail turn to 362
Leave it well alone turn to 561
Cross the silver nugget

**Additional context**

### LINKED ISSUE #58: Section 506 Book 1
```
The Gold Dust Tavern is a plush inn besides the city gates. Thetavern  costs  you  1  Shard  a  day.  Each  day  you  spend  here,  youcan  recover  1  Stamina  point  if  injured,  up  to  the  limit  of  yournormal unwounded Stamina score.If  you  want  to  spend  a  further  3  Shards  buying  drinks  allround at the bar, and listen for rumours, turn to 331. Otherwise,turn to 10.
```

**Reference features required (if any)**
If you want to spend a further 3 Shards buying drinks all round at the bar, and listen for rumours, turn to 331.
Otherwise, turn to 10.

**Additional context**
Tavern costs you 1 Shard a day
Each day you spend here, you can recover 1 Stamina point if injured, up to the limit of your normal unwounded Stamina score.

### LINKED ISSUE #64: Section 507 Book 1
```
You are sailing across the Sea of Whispers with a clear, blue sky
and a salty wind to help you on your way.
Dock at the Isle of Druids turn to 195
Sail west towards Scorpion Bight turn to 430
Sail north west into coastal waters turn to 190
Sail north into coastal waters turn to 312
Sail south into the Violet Ocean turn to 13
Sail east into the Unbounded Ocean turn to 206
```

**Reference features required (if any)**
Dock at the Isle of Druids turn to 195
Sail west towards Scorpion Bight turn to 430
Sail north west into coastal waters turn to 190
Sail north into coastal waters turn to 312
Sail south into the Violet Ocean turn to 13
Sail east into the Unbounded Ocean turn to 206

**Additional context**
sailing across the Sea

### LINKED ISSUE #144: Section 510 Book 1
```
The village of Blessed Springs, nestling at the foot of a tall hill,
has grown up around the holy waters, a special spring said to
have healing powers. It has been fenced off by the villagers, and
a priesthood appointed to supervise the supplicants who come to
bathe, or drink of the spring’s waters. There is no market, but an
alchemist has set up shop here.
Visit the Holy Waters turn to 450
Visit the alchemist’s shop turn to 342
Visit the Blessed Ale Tavern turn to 483
Explore the hill turn to 398
Head north towards Fort Brilon turn to 466
South towards to Venefax turn to 87
West into the countryside turn to 278
North west into farmlands turn to 548
```

**Reference features required (if any)**
Visit the Holy Waters turn to 450
Visit the alchemist’s shop turn to 342
Visit the Blessed Ale Tavern turn to 483
Explore the hill turn to 398
Head north towards Fort Brilon turn to 466
South towards to Venefax turn to 87
West into the countryside turn to 278
North west into farmlands turn to 548

**Additional context**

### LINKED ISSUE #174: Section 513 Book 1
```
One of them gives you a conch shell full of a greenish liquid.
You drink it, and dive into the sea. Miraculously, you can
breathe underwater! You follow the sea centaurs down into the
depths until you arrive at a sunken ship, which is encrusted in
barnacles and seaweed.
Suddenly, the sea centaurs swim away, leaving you alone.
You notice that you are giving off a glow like the sea centaurs.
Looking down, you see that the lower half of your body has
turned into that of a sea centaur! You have been taken and
transformed to replace their lost companion.
Explore the sunken wreck turn to 429
Swim back up to your ship turn to 616
```

**Reference features required (if any)**
Explore the sunken wreck turn to 429
Swim back up to your ship turn to 616

**Additional context**

### LINKED ISSUE #465: Section 516 Book 1
```
You pull the wolf pelt over you, and drop to all fours.
Gingerly, you crawl in. In the dark, you now look and smell like
a wolf. At the back of the cave, you find a hole in the roof and
an iron ladder leading up to it.
Climb the ladder The Plains of Howling Darkness 350
Leave the cave turn to 3

```

**Reference features required (if any)**
Climb the ladder The Plains of Howling Darkness 350
Leave the cave turn to 3

**Additional context**

### LINKED ISSUE #468: Section 517 Book 1
```
If you have a ghoul’s head , turn to 597 . If not, a priest asks
which service you require.
Become an initiate turn to 409
Renounce worship turn to 187
Make resurrection arrangements turn to 478
Leave the temple turn to 100
```

**Reference features required (if any)**
If you have a ghoul’s head , turn to 597 . If not, a priest askswhich service you require.
Become an initiate turn to 409
Renounce worship turn to 187
Make resurrection arrangements turn to 478
Leave the temple turn to 100

**Additional context**

### LINKED ISSUE #473: Section 521 Book 1
```
You are looking for the Black Dragon Knight on a quest that
was set for you by Yanryt the Son. You ask the knights if he is
here.
‘The Black Dragon Knight? Yes, he is,’ replies one of them.
‘But he fights only to the death – there is no wager save the
greatest of all for him, that is to say, life itself.’
Fight the Black Dragon Knight turn to 321
Don’t fight and leave instead turn to 276
```

**Reference features required (if any)**
Fight the Black Dragon Knight turn to 321
Don’t fight and leave instead turn to 276

**Additional context**

### LINKED ISSUE #474: Section 522 Book 1
```
That night several sea centaurs emerge from the waters, their
spiny skins glittering with phosphorescent flashes of light.
One of them speaks in a burbling voice. ‘Where is our
brother, whom you caught in your cruel nets, this day?’
‘He is dead, I’m afraid’, you reply, readying yourself for a
fight.
The sea centaurs remain silent for a few moments, then the
leader says, ‘His destiny was always bleak. We would be grateful
if you were to return his body to us.’
You cannot think of a reason not to, so you pass the body
down to them.
‘We thank you,’ burbles the sea centaur. ‘If you wish, we
will give you the power to breathe the waters, so that you may
swim down to the wreck that lies below, and take its treasures,
those things that the surface-dwellers hold dear.’
Accept the offer turn to 513
Refuse the offer turn to 408
```

**Reference features required (if any)**
Accept the offer turn to 513
Refuse the offer turn to 408

**Additional context**

### LINKED ISSUE #477: Section 524 Book 1
```
You struggle on. Only your iron will and hardiness keep you
alive. Eventually, the path leads to a bubbling well of spring-
water in the rocks, just at the opening of a cave. You drink your
fill, and soon you feel much better. Turn to 232 .
```

**Reference features required (if any)**
 You drink your fill, and soon you feel much better. Turn to 232 .

**Additional context**

### LINKED ISSUE #478: Section 525 Book 1
```
‘They’re vicious, evil devils,’ says an old peasant. ‘Like huge
scorpions they are, save they have the head and shoulders of a
man – intelligent too, forever seeking to pillage our town, but
they can’t climb up the ladders!”
A soldier in the local militia speaks up, ‘They hate fire, too.
All we have to do is sit atop the town, and pepper them with
flaming arrows. They can’t stand that for long. Mind you, things
are getting bad – they’ve got a sorcerer now!’
A young man, blind in one eye and paralysed down one side,
says, ‘They got a terrible sting as well – their venom did this to
me,’ pointing at his eye and side.
There’s not much else to hear, so you leave. Turn to 427 .
```

**Reference features required (if any)**
There’s not much else to hear, so you leave. Turn to 427 .

**Additional context**

### LINKED ISSUE #479: Section 526 Book 1
```
The temple of Tyrnai, the God of War, is built in the shape of a
spear with a long, pillared nave, and an altar at the far end. Two
massive stone warriors guard its gates.
Tyrnai is depicted here as the insensate spirit of war – a
blood-drenched warrior with the head of a maddened jaguar.
Become an initiate turn to 435
Renounce his worship turn to 69.
Seek a blessing turn to 373
Make resurrection arrangements turn to 599
Leave the temple turn to 10
```

**Reference features required (if any)**
Become an initiate turn to 435
Renounce his worship turn to 69
Seek a blessing turn to 373
Make resurrection arrangements turn to 599
Leave the temple

**Additional context**

### LINKED ISSUE #520: Section 527 Book 1
```
You run off, leaving the terrible Gob-gobbler behind. The
villagers of Venefax greet you with snorts of derision and
contempt, and the young boy, Mikail, looks away, disappointed.
It would be prudent to leave Venefax for a while.
South into Scorpion Bight turn to 492
North east towards Blessed Springs turn to 87
South west on the road to Yellowport turn to 621
North into open countryside turn to 278
```

**Reference features required (if any)**
South into Scorpion Bight turn to 492
North east towards Blessed Springs turn to 87
South west on the road to Yellowport turn to 621
North into open countryside turn to 278

**Additional context**

### LINKED ISSUE #526: Section 531 Book 1
```
If you have a golden net , turn to 4 . If you do not have one,
turn to 462 .
```

**Reference features required (if any)**
If you have a golden net , turn to 4 . If you do not have one,
turn to 462 .

**Additional context**

### LINKED ISSUE #532: Section 533 Book 1
```
The man takes the money, bites a coin and spits. Satisfied he
says, ‘The Witches’ Cauldron – that’s where you’ll find him.’
Later, you find the Witches’ Cauldron Tavern in a maze of
backstreets. Looking through a window, you spot a man with a
velvet eyepatch sitting at a table, eating a meal.
Walk in and challenge him turn to 589
Ambush him when he leaves turn to 211
```

**Reference features required (if any)**
Walk in and challenge him turn to 589
Ambush him when he leaves turn to 211

**Additional context**

### LINKED ISSUE #533: Section 534 Book 1
```
A long time passes. After a while, you risk calling up to Lauria in
a whisper. Your voice sounds thick, rasping – choked with
growing fear. Lauria does not reply.
Each second you remain in the house increases the risk of
discovery.
Wait a little longer turn to 119
Go upstairs to find Lauria turn to 386
Leave at once turn to 10
```

**Reference features required (if any)**
Wait a little longer turn to 119
Go upstairs to find Lauria turn to 386
Leave at once turn to 10

**Additional context**

### LINKED ISSUE #539: Section 540 Book 1
```
Sure enough, when the scholar leaves, purse bulging with
Shards, the two ruffians also leave. You follow at a slight
distance. As you suspected, the ruffians wait for a suitable
moment and then set about the scholar.
‘Help, help! Thieves!’ cries the scholar in a thin, reedy voice.
Return to the city centre turn to 100
Chase the muggers off turn to 433
```

**Reference features required (if any)**
Return to the city centre turn to 100
Chase the muggers off turn to 433

**Additional context**

### PR DESCRIPTION
**Pull request by Noeell**
### What?
Implemented the easy sections that are already possible to implement
### Anything Else?
closes #51 
closes #58 
closes #64 
closes #144 
closes #174 
closes #465 
closes #468 
closes #473 
closes #474 
closes #477 
closes #478 
closes #479 
closes #520 
closes #526 
closes #532 
closes #533 
closes #539

### CODE REVIEW

**Review by JJoeeyy — APPROVED** [review]
good work with the easy ones

**Review by Nilstrieb — APPROVED** [review]

**Review by Lion-alt — APPROVED** [review]
LGTM 👍

**Review by nnikolajj — APPROVED** [review]
Chatgpt sagt ist gut

**Review by MagischerWolf05 — APPROVED** [review]
👍🏽

**Pull request merged**
